import { auth } from '@/auth';
import { Toaster } from '@/components/ui/sonner';
import { TrpcProvider } from '@/utils/trpc-client';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session || !session.user) {
    // navigate to the login page
    redirect('/api/auth/signin');
  }

  return (
    <html lang='en'>
      <body className='font-sans'>
        <Toaster />
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  );
}
